---
# Tomcat install documentation can be found here.
# note this is version 9
# source: https://tomcat.apache.org/tomcat-9.0-doc/building.html

# https://stackoverflow.com/questions/32942023/ubuntu-openjdk-8-unable-to-locate-package
- name: Install Java
  package:
    pkg: "{{ item }}"
    state: present
  loop:
    # - openjdk-8-jdk
    # - openjdk-8-doc
    # - openjdk-8-jre-lib
    - oracle-java8-installer

# https://ant.apache.org/
# srouce: https://websiteforstudents.com/how-to-install-apache-ant-on-ubuntu-18-04-16-04/
- name: Install Apache Ant
  package:
    pkg: "{{ item }}"
    state: present
  loop:
    - ant

# download Tomcat source

# config

# Build Tomcat
