---
# Tomcat install documentation can be found here.
# Tomcat Version: 9
# Java Version: 8
# source: https://tomcat.apache.org/tomcat-9.0-doc/building.html

- debug:
    msg: Java install prep

- debug:
    msg: "source: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04"

- name: Install Java
  package:
    pkg: "{{ item }}"
    state: present
  loop:
    # - oracle-java8-installer
    - openjdk-8-jre-headless
    - openjdk-8-jdk


# https://ant.apache.org/
# srouce: https://websiteforstudents.com/how-to-install-apache-ant-on-ubuntu-18-04-16-04/
- name: Install Apache Ant
  package:
    pkg: "{{ item }}"
    state: present
  loop:
    - ant

- name: Download Tomcat
  get_url:
    url: https://mirrors.ocf.berkeley.edu/apache/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz
    dest: /opt/apache-tomcat-9.0.35.tar.gz
    checksum: sha512:0db27185d9fc3174f2c670f814df3dda8a008b89d1a38a5d96cbbe119767ebfb1cf0bce956b27954aee9be19c4a7b91f2579d967932207976322033a86075f98

- name: Make tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0777

- name: Extract apache-tomcat-9.0.35.tar.gz to /top/tomcat
  unarchive:
    src: /opt/apache-tomcat-9.0.35.tar.gz
    dest: /opt/tomcat

# config

# Build Tomcat
